# Generated by Django 5.1 on 2024-08-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Hey', max_length=200),
            preserve_default=False,
        ),
    ]
